export const countryCodes = [
  {
    name: "South Sudan",
    dial_code: "South Sudan (+211)",
    emoji: "🇸🇸",
    code: "SS",
  },
  {
    name: "Afghanistan",
    dial_code: "Afghanistan (+93)",
    emoji: "🇦🇫",
    code: "AF",
  },
  {
    name: "Aland Islands",
    dial_code: "Aland Islands (+358)",
    emoji: "🇦🇽",
    code: "AX",
  },
  {
    name: "Albania",
    dial_code: "Albania (+355)",
    emoji: "🇦🇱",
    code: "AL",
  },
  {
    name: "Algeria",
    dial_code: "Algeria (+213)",
    emoji: "🇩🇿",
    code: "DZ",
  },
  {
    name: "AmericanSamoa",
    dial_code: "AmericanSamoa (+1684)",
    emoji: "🇦🇸",
    code: "AS",
  },
  {
    name: "Andorra",
    dial_code: "Andorra (+376)",
    emoji: "🇦🇩",
    code: "AD",
  },
  {
    name: "Angola",
    dial_code: "Angola (+244)",
    emoji: "🇦🇴",
    code: "AO",
  },
  {
    name: "Anguilla",
    dial_code: "Anguilla (+1264)",
    emoji: "🇦🇮",
    code: "AI",
  },
  {
    name: "Antarctica",
    dial_code: "Antarctica (+672)",
    emoji: "🇦🇶",
    code: "AQ",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "Antigua and Barbuda (+1268)",
    emoji: "🇦🇬",
    code: "AG",
  },
  {
    name: "Argentina",
    dial_code: "Argentina (+54)",
    emoji: "🇦🇷",
    code: "AR",
  },
  {
    name: "Armenia",
    dial_code: "Armenia (+374)",
    emoji: "🇦🇲",
    code: "AM",
  },
  {
    name: "Aruba",
    dial_code: "Aruba (+297)",
    emoji: "🇦🇼",
    code: "AW",
  },
  {
    name: "Australia",
    dial_code: "Australia (+61)",
    emoji: "🇦🇺",
    code: "AU",
  },
  {
    name: "Austria",
    dial_code: "Austria (+43)",
    emoji: "🇦🇹",
    code: "AT",
  },
  {
    name: "Azerbaijan",
    dial_code: "Azerbaijan (+994)",
    emoji: "🇦🇿",
    code: "AZ",
  },
  {
    name: "Bahamas",
    dial_code: "Bahamas (+1242)",
    emoji: "🇧🇸",
    code: "BS",
  },
  {
    name: "Bahrain",
    dial_code: "Bahrain (+973)",
    emoji: "🇧🇭",
    code: "BH",
  },
  {
    name: "Bangladesh",
    dial_code: "Bangladesh (+880)",
    emoji: "🇧🇩",
    code: "BD",
  },
  {
    name: "Barbados",
    dial_code: "Barbados (+1246)",
    emoji: "🇧🇧",
    code: "BB",
  },
  {
    name: "Belarus",
    dial_code: "Belarus (+375)",
    emoji: "🇧🇾",
    code: "BY",
  },
  {
    name: "Belgium",
    dial_code: "Belgium (+32)",
    emoji: "🇧🇪",
    code: "BE",
  },
  {
    name: "Belize",
    dial_code: "Belize (+501)",
    emoji: "🇧🇿",
    code: "BZ",
  },
  {
    name: "Benin",
    dial_code: "Benin (+229)",
    emoji: "🇧🇯",
    code: "BJ",
  },
  {
    name: "Bermuda",
    dial_code: "Bermuda (+1441)",
    emoji: "🇧🇲",
    code: "BM",
  },
  {
    name: "Bhutan",
    dial_code: "Bhutan (+975)",
    emoji: "🇧🇹",
    code: "BT",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "Bolivia (+591)",
    emoji: "🇧🇴",
    code: "BO",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "Bosnia (+387)",
    emoji: "🇧🇦",
    code: "BA",
  },
  {
    name: "Botswana",
    dial_code: "Botswana (+267)",
    emoji: "🇧🇼",
    code: "BW",
  },
  {
    name: "Brazil",
    dial_code: "Brazil (+55)",
    emoji: "🇧🇷",
    code: "BR",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "British Indian Ocean Territory (+246)",
    emoji: "🇮🇴",
    code: "IO",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "Brunei (+673)",
    emoji: "🇧🇳",
    code: "BN",
  },
  {
    name: "Bulgaria",
    dial_code: "Bulgaria (+359)",
    emoji: "🇧🇬",
    code: "BG",
  },
  {
    name: "Burkina Faso",
    dial_code: "Burkina Faso (+226)",
    emoji: "🇧🇫",
    code: "BF",
  },
  {
    name: "Burundi",
    dial_code: "Burundi (+257)",
    emoji: "🇧🇮",
    code: "BI",
  },
  {
    name: "Cambodia",
    dial_code: "Cambodia (+855)",
    emoji: "🇰🇭",
    code: "KH",
  },
  {
    name: "Cameroon",
    dial_code: "Cameroon (+237)",
    emoji: "🇨🇲",
    code: "CM",
  },
  {
    name: "Canada",
    dial_code: "Canada (+1)",
    emoji: "🇨🇦",
    code: "CA",
  },
  {
    name: "Cape Verde",
    dial_code: "Cape Verde (+238)",
    emoji: "🇨🇻",
    code: "CV",
  },
  {
    name: "Cayman Islands",
    dial_code: "Cayman Islands (+345)",
    emoji: "🇰🇾",
    code: "KY",
  },
  {
    name: "Central African Republic",
    dial_code: "Central African Republic (+236)",
    emoji: "🇨🇫",
    code: "CF",
  },
  {
    name: "Chad",
    dial_code: "Chad (+235)",
    emoji: "🇹🇩",
    code: "TD",
  },
  {
    name: "Chile",
    dial_code: "Chile (+56)",
    emoji: "🇨🇱",
    code: "CL",
  },
  {
    name: "China",
    dial_code: "China (+86)",
    emoji: "🇨🇳",
    code: "CN",
  },
  {
    name: "Christmas Island",
    dial_code: "Christmas Island (+61)",
    emoji: "🇨🇽",
    code: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "Cocos Islands (+61)",
    emoji: "🇨🇨",
    code: "CC",
  },
  {
    name: "Colombia",
    dial_code: "Colombia (+57)",
    emoji: "🇨🇴",
    code: "CO",
  },
  {
    name: "Comoros",
    dial_code: "Comoros (+269)",
    emoji: "🇰🇲",
    code: "KM",
  },
  {
    name: "Congo",
    dial_code: "Congo (+242)",
    emoji: "🇨🇬",
    code: "CG",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "DRC (+243)",
    emoji: "🇨🇩",
    code: "CD",
  },
  {
    name: "Cook Islands",
    dial_code: "Cook Islands (+682)",
    emoji: "🇨🇰",
    code: "CK",
  },
  {
    name: "Costa Rica",
    dial_code: "Costa Rica (+506)",
    emoji: "🇨🇷",
    code: "CR",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "Cote d'Ivoire (+225)",
    emoji: "🇨🇮",
    code: "CI",
  },
  {
    name: "Croatia",
    dial_code: "Croatia (+385)",
    emoji: "🇭🇷",
    code: "HR",
  },
  {
    name: "Cuba",
    dial_code: "Cuba (+53)",
    emoji: "🇨🇺",
    code: "CU",
  },
  {
    name: "Cyprus",
    dial_code: "Cyprus (+357)",
    emoji: "🇨🇾",
    code: "CY",
  },
  {
    name: "Czech Republic",
    dial_code: "Czech Republic (+420)",
    emoji: "🇨🇿",
    code: "CZ",
  },
  {
    name: "Denmark",
    dial_code: "Denmark (+45)",
    emoji: "🇩🇰",
    code: "DK",
  },
  {
    name: "Djibouti",
    dial_code: "Djibouti (+253)",
    emoji: "🇩🇯",
    code: "DJ",
  },
  {
    name: "Dominica",
    dial_code: "Dominica (+1767)",
    emoji: "🇩🇲",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    dial_code: "Dominican Republic (+1849)",
    emoji: "🇩🇴",
    code: "DO",
  },
  {
    name: "Ecuador",
    dial_code: "Ecuador (+593)",
    emoji: "🇪🇨",
    code: "EC",
  },
  {
    name: "Egypt",
    dial_code: "Egypt (+20)",
    emoji: "🇪🇬",
    code: "EG",
  },
  {
    name: "El Salvador",
    dial_code: "El Salvador (+503)",
    emoji: "🇸🇻",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "Equatorial Guinea (+240)",
    emoji: "🇬🇶",
    code: "GQ",
  },
  {
    name: "Eritrea",
    dial_code: "Eritrea (+291)",
    emoji: "🇪🇷",
    code: "ER",
  },
  {
    name: "Estonia",
    dial_code: "Estonia (+372)",
    emoji: "🇪🇪",
    code: "EE",
  },
  {
    name: "Ethiopia",
    dial_code: "Ethiopia (+251)",
    emoji: "🇪🇹",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "Falkland Islands (+500)",
    emoji: "🇫🇰",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    dial_code: "Faroe Islands (+298)",
    emoji: "🇫🇴",
    code: "FO",
  },
  {
    name: "Fiji",
    dial_code: "Fiji (+679)",
    emoji: "🇫🇯",
    code: "FJ",
  },
  {
    name: "Finland",
    dial_code: "Finland (+358)",
    emoji: "🇫🇮",
    code: "FI",
  },
  {
    name: "France",
    dial_code: "France (+33)",
    emoji: "🇫🇷",
    code: "FR",
  },
  {
    name: "French Guiana",
    dial_code: "French Guiana (+594)",
    emoji: "🇬🇫",
    code: "GF",
  },
  {
    name: "French Polynesia",
    dial_code: "French Polynesia (+689)",
    emoji: "🇵🇫",
    code: "PF",
  },
  {
    name: "Gabon",
    dial_code: "Gabon (+241)",
    emoji: "🇬🇦",
    code: "GA",
  },
  {
    name: "Gambia",
    dial_code: "Gambia (+220)",
    emoji: "🇬🇲",
    code: "GM",
  },
  {
    name: "Georgia",
    dial_code: "Georgia (+995)",
    emoji: "🇬🇪",
    code: "GE",
  },
  {
    name: "Germany",
    dial_code: "Germany (+49)",
    emoji: "🇩🇪",
    code: "DE",
  },
  {
    name: "Ghana",
    dial_code: "Ghana (+233)",
    emoji: "🇬🇭",
    code: "GH",
  },
  {
    name: "Gibraltar",
    dial_code: "Gibraltar (+350)",
    emoji: "🇬🇮",
    code: "GI",
  },
  {
    name: "Greece",
    dial_code: "Greece (+30)",
    emoji: "🇬🇷",
    code: "GR",
  },
  {
    name: "Greenland",
    dial_code: "Greenland (+299)",
    emoji: "🇬🇱",
    code: "GL",
  },
  {
    name: "Grenada",
    dial_code: "Grenada (+1473)",
    emoji: "🇬🇩",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    dial_code: "Guadeloupe (+590)",
    emoji: "🇬🇵",
    code: "GP",
  },
  {
    name: "Guam",
    dial_code: "Guam (+1671)",
    emoji: "🇬🇺",
    code: "GU",
  },
  {
    name: "Guatemala",
    dial_code: "Guatemala (+502)",
    emoji: "🇬🇹",
    code: "GT",
  },
  {
    name: "Guernsey",
    dial_code: "Guernsey (+44)",
    emoji: "🇬🇬",
    code: "GG",
  },
  {
    name: "Guinea",
    dial_code: "Guinea (+224)",
    emoji: "🇬🇳",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "Guinea-Bissau (+245)",
    emoji: "🇬🇼",
    code: "GW",
  },
  {
    name: "Guyana",
    dial_code: "Guyana (+595)",
    emoji: "🇬🇾",
    code: "GY",
  },
  {
    name: "Haiti",
    dial_code: "Haiti (+509)",
    emoji: "🇭🇹",
    code: "HT",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "Holy See (+379)",
    emoji: "🇻🇦",
    code: "VA",
  },
  {
    name: "Honduras",
    dial_code: "Honduras (+504)",
    emoji: "🇭🇳",
    code: "HN",
  },
  {
    name: "Hong Kong",
    dial_code: "Hong Kong (+852)",
    emoji: "🇭🇰",
    code: "HK",
  },
  {
    name: "Hungary",
    dial_code: "Hungary (+36)",
    emoji: "🇭🇺",
    code: "HU",
  },
  {
    name: "Iceland",
    dial_code: "Iceland (+354)",
    emoji: "🇮🇸",
    code: "IS",
  },
  {
    name: "India",
    dial_code: "India (+91)",
    emoji: "🇮🇳",
    code: "IN",
  },
  {
    name: "Indonesia",
    dial_code: "Indonesia (+62)",
    emoji: "🇮🇩",
    code: "ID",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "Iran, IR (+98)",
    emoji: "🇮🇷",
    code: "IR",
  },
  {
    name: "Iraq",
    dial_code: "Iraq, IQ (+964)",
    emoji: "🇮🇷",
    code: "IQ",
  },
  {
    name: "Ireland",
    dial_code: "Ireland (+353)",
    emoji: "🇮🇪",
    code: "IE",
  },
  {
    name: "Isle of Man",
    dial_code: "Isle of Man (+44)",
    emoji: "🇮🇲",
    code: "IM",
  },
  {
    name: "Israel",
    dial_code: "Israel (+972)",
    emoji: "🇮🇱",
    code: "IL",
  },
  {
    name: "Italy",
    dial_code: "Italy (+39)",
    emoji: "🇮🇹",
    code: "IT",
  },
  {
    name: "Jamaica",
    dial_code: "Jamaica (+1876)",
    emoji: "🇯🇲",
    code: "JM",
  },
  {
    name: "Japan",
    dial_code: "Japan (+81)",
    emoji: "🇯🇵",
    code: "JP",
  },
  {
    name: "Jersey",
    dial_code: "Jersey (+44)",
    emoji: "🇯🇪",
    code: "JE",
  },
  {
    name: "Jordan",
    dial_code: "Jordan (+962)",
    emoji: "🇯🇴",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    dial_code: "Kazakhstan (+77)",
    emoji: "🇰🇿",
    code: "KZ",
  },
  {
    name: "Kenya",
    dial_code: "Kenya (+254)",
    emoji: "🇰🇪",
    code: "KE",
  },
  {
    name: "Kiribati",
    dial_code: "Kiribati (+686)",
    emoji: "🇰🇮",
    code: "KI",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "Korea, KP (+850)",
    emoji: "🇰🇵",
    code: "KP",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "Korea, KR (+82)",
    emoji: "🇰🇷",
    code: "KR",
  },
  {
    name: "Kuwait",
    dial_code: "Kuwait (+965)",
    emoji: "🇰🇼",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "Kyrgyzstan (+996)",
    emoji: "🇰🇬",
    code: "KG",
  },
  {
    name: "Laos",
    dial_code: "Laos (+856)",
    emoji: "🇱🇦",
    code: "LA",
  },
  {
    name: "Latvia",
    dial_code: "Latvia (+371)",
    emoji: "🇱🇻",
    code: "LV",
  },
  {
    name: "Lebanon",
    dial_code: "Lebanon (+961)",
    emoji: "🇱🇧",
    code: "LB",
  },
  {
    name: "Lesotho",
    dial_code: "Lesotho (+266)",
    emoji: "🇱🇸",
    code: "LS",
  },
  {
    name: "Liberia",
    dial_code: "Liberia (+231)",
    emoji: "🇱🇷",
    code: "LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "Libyan Arab Jamahiriya (+218)",
    emoji: "🇱🇾",
    code: "LY",
  },
  {
    name: "Liechtenstein",
    dial_code: "Liechtenstein (+423)",
    emoji: "🇱🇮",
    code: "LI",
  },
  {
    name: "Lithuania",
    dial_code: "Lithuania (+370)",
    emoji: "🇱🇹",
    code: "LT",
  },
  {
    name: "Luxembourg",
    dial_code: "Luxembourg (+352)",
    emoji: "🇱🇺",
    code: "LU",
  },
  {
    name: "Macao",
    dial_code: "Macao (+853)",
    emoji: "🇲🇴",
    code: "MO",
  },
  {
    name: "Macedonia",
    dial_code: "Macedonia (+389)",
    emoji: "🇲🇰",
    code: "MK",
  },
  {
    name: "Madagascar",
    dial_code: "Madagascar (+261)",
    emoji: "🇲🇬",
    code: "MG",
  },
  {
    name: "Malawi",
    dial_code: "Malawi (+265)",
    emoji: "🇲🇼",
    code: "MW",
  },
  {
    name: "Malaysia",
    dial_code: "Malaysia (+60)",
    emoji: "🇲🇾",
    code: "MY",
  },
  {
    name: "Maldives",
    dial_code: "Maldives (+960)",
    emoji: "🇲🇻",
    code: "MV",
  },
  {
    name: "Mali",
    dial_code: "Mali (+223)",
    emoji: "🇲🇱",
    code: "ML",
  },
  {
    name: "Malta",
    dial_code: "Malta (+356)",
    emoji: "🇲🇹",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    dial_code: "Marshall Islands (+692)",
    emoji: "🇲🇭",
    code: "MH",
  },
  {
    name: "Martinique",
    dial_code: "Martinique (+596)",
    emoji: "🇲🇶",
    code: "MQ",
  },
  {
    name: "Mauritania",
    dial_code: "Mauritania (+222)",
    emoji: "🇲🇷",
    code: "MR",
  },
  {
    name: "Mauritius",
    dial_code: "Mauritius (+230)",
    emoji: "🇲🇺",
    code: "MU",
  },
  {
    name: "Mayotte",
    dial_code: "Mayotte (+262)",
    emoji: "🇾🇹",
    code: "YT",
  },
  {
    name: "Mexico",
    dial_code: "Mexico (+52)",
    emoji: "🇲🇽",
    code: "MX",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "Micronesia (+691)",
    emoji: "🇫🇲",
    code: "FM",
  },
  {
    name: "Moldova",
    dial_code: "Moldova (+373)",
    emoji: "🇲🇩",
    code: "MD",
  },
  {
    name: "Monaco",
    dial_code: "Monaco (+377)",
    emoji: "🇲🇨",
    code: "MC",
  },
  {
    name: "Mongolia",
    dial_code: "Mongolia (+976)",
    emoji: "🇲🇳",
    code: "MN",
  },
  {
    name: "Montenegro",
    dial_code: "Montenegro (+382)",
    emoji: "🇲🇪",
    code: "ME",
  },
  {
    name: "Montserrat",
    dial_code: "Montserrat (+1664)",
    emoji: "🇲🇸",
    code: "MS",
  },
  {
    name: "Morocco",
    dial_code: "Morocco (+212)",
    emoji: "🇲🇦",
    code: "MA",
  },
  {
    name: "Mozambique",
    dial_code: "Mozambique (+258)",
    emoji: "🇲🇿",
    code: "MZ",
  },
  {
    name: "Myanmar",
    dial_code: "Myanmar (+95)",
    emoji: "🇲🇲",
    code: "MM",
  },
  {
    name: "Namibia",
    emoji: "🇳🇦",
    dial_code: "Namibia (+264)",
    code: "NA",
  },
  {
    name: "Nauru",
    dial_code: "Nauru (+674)",
    emoji: "🇳🇷",
    code: "NR",
  },
  {
    name: "Nepal",
    dial_code: "Nepal (+977)",
    emoji: "🇳🇵",
    code: "NP",
  },
  {
    name: "Netherlands",
    dial_code: "Netherlands (+31)",
    emoji: "🇳🇱",
    code: "NL",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "Netherlands Antilles (+599)",
    emoji: "🇧🇶",
    code: "AN",
  },
  {
    name: "New Caledonia",
    dial_code: "New Caledonia (+687)",
    emoji: "🇳🇨",
    code: "NC",
  },
  {
    name: "New Zealand",
    dial_code: "New Zealand (+64)",
    emoji: "🇳🇿",
    code: "NZ",
  },
  {
    name: "Nicaragua",
    dial_code: "Nicaragua (+505)",
    emoji: "🇳🇮",
    code: "NI",
  },
  {
    name: "Niger",
    dial_code: "Niger (+227)",
    emoji: "🇳🇪",
    code: "NE",
  },
  {
    name: "Nigeria",
    dial_code: "Nigeria (+234)",
    emoji: "🇳🇬",
    code: "NG",
  },
  {
    name: "Niue",
    dial_code: "Niue (+683)",
    emoji: "🇳🇺",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    dial_code: "Norfolk Island (+672)",
    emoji: "🇳🇫",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "Northern Mariana Islands (+1670)",
    emoji: "🇲🇵",
    code: "MP",
  },
  {
    name: "Norway",
    dial_code: "Norway (+47)",
    emoji: "🇳🇴",
    code: "NO",
  },
  {
    name: "Oman",
    dial_code: "Oman (+968)",
    emoji: "🇴🇲",
    code: "OM",
  },
  {
    name: "Pakistan",
    dial_code: "Pakistan (+92)",
    emoji: "🇵🇰",
    code: "PK",
  },
  {
    name: "Palau",
    dial_code: "Palau (+680)",
    emoji: "🇵🇼",
    code: "PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "Palestinian Territory (+970)",
    emoji: "🇵🇸",
    code: "PS",
  },
  {
    name: "Panama",
    dial_code: "Panama (+507)",
    emoji: "🇵🇦",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    dial_code: "Papua New Guinea (+675)",
    emoji: "🇵🇬",
    code: "PG",
  },
  {
    name: "Paraguay",
    dial_code: "Paraguay (+595)",
    emoji: "🇵🇾",
    code: "PY",
  },
  {
    name: "Peru",
    dial_code: "Peru (+51)",
    emoji: "🇵🇪",
    code: "PE",
  },
  {
    name: "Philippines",
    dial_code: "Philippines (+63)",
    emoji: "🇵🇭",
    code: "PH",
  },
  {
    name: "Pitcairn",
    dial_code: "Pitcairn (+872)",
    emoji: "🇵🇳",
    code: "PN",
  },
  {
    name: "Poland",
    dial_code: "Poland (+48)",
    emoji: "🇵🇱",
    code: "PL",
  },
  {
    name: "Portugal",
    dial_code: "Portugal (+351)",
    emoji: "🇵🇹",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    dial_code: "Puerto Rico (+1939)",
    emoji: "🇵🇷",
    code: "PR",
  },
  {
    name: "Qatar",
    dial_code: "Qatar (+974)",
    emoji: "🇶🇦",
    code: "QA",
  },
  {
    name: "Romania",
    dial_code: "Romania (+40)",
    emoji: "🇷🇴",
    code: "RO",
  },
  {
    name: "Russia",
    dial_code: "Russia (+7)",
    emoji: "🇷🇺",
    code: "RU",
  },
  {
    name: "Rwanda",
    dial_code: "Rwanda (+250)",
    emoji: "🇷🇼",
    code: "RW",
  },
  {
    name: "Reunion",
    dial_code: "Reunion (+262)",
    emoji: "🇷🇪",
    code: "RE",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "Saint Barthelemy (+590)",
    emoji: "🇧🇱",
    code: "BL",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "Saint Helena (+290)",
    emoji: "🇸🇭",
    code: "SH",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "Saint Kitts and Nevis(+1869)",
    emoji: "🇰🇳",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    dial_code: "Saint Lucia (+1758)",
    emoji: "🇱🇨",
    code: "LC",
  },
  {
    name: "Saint Martin",
    dial_code: "Saint Martin (+590)",
    emoji: "🇲🇫",
    code: "MF",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "Saint Pierre and Miquelon(+508)",
    emoji: "🇵🇲",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "Saint Vincent(+1784)",
    emoji: "🇻🇨",
    code: "VC",
  },
  {
    name: "Samoa",
    dial_code: "Samoa (+685)",
    emoji: "🇼🇸",
    code: "WS",
  },
  {
    name: "San Marino",
    dial_code: "San Marino (+378)",
    emoji: "🇸🇲",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "Sao Tome and Principe (+239)",
    emoji: "🇸🇹",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    dial_code: "Saudi Arabia (+966)",
    emoji: "🇸🇦",
    code: "SA",
  },
  {
    name: "Senegal",
    dial_code: "Senegal (+221)",
    emoji: "🇸🇳",
    code: "SN",
  },
  {
    name: "Serbia",
    dial_code: "Serbia (+381)",
    emoji: "🇷🇸",
    code: "RS",
  },
  {
    name: "Seychelles",
    dial_code: "Seychelles (+248)",
    emoji: "🇸🇨",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    dial_code: "Sierra Leone (+232)",
    emoji: "🇸🇱",
    code: "SL",
  },
  {
    name: "Singapore",
    dial_code: "Singapore (+65)",
    emoji: "🇸🇬",
    code: "SG",
  },
  {
    name: "Slovakia",
    dial_code: "Slovakia (+421)",
    emoji: "🇸🇰",
    code: "SK",
  },
  {
    name: "Slovenia",
    dial_code: "Slovenia (+386)",
    emoji: "🇸🇮",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    dial_code: "Solomon Islands (+677)",
    emoji: "🇸🇧",
    code: "SB",
  },
  {
    name: "Somalia",
    dial_code: "Somalia (+252)",
    emoji: "🇸🇴",
    code: "SO",
  },
  {
    name: "South Africa",
    dial_code: "South Africa (+27)",
    emoji: "🇿🇦",
    code: "ZA",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "South Georgia, GS (+500)",
    emoji: "🇬🇸",
    code: "GS",
  },
  {
    name: "Spain",
    dial_code: "Spain (+34)",
    emoji: "🇪🇸",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    dial_code: "Sri Lanka (+94)",
    emoji: "🇱🇰",
    code: "LK",
  },
  {
    name: "Sudan",
    dial_code: "Sudan (+249)",
    emoji: "🇸🇩",
    code: "SD",
  },
  {
    name: "Suriname",
    dial_code: "Suriname (+597)",
    emoji: "🇸🇷",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "Svalbard and Jan Mayen (+47)",
    emoji: "🇸🇯",
    code: "SJ",
  },
  {
    name: "Swaziland",
    dial_code: "Swaziland (+268)",
    emoji: "🇸🇿",
    code: "SZ",
  },
  {
    name: "Sweden",
    dial_code: "Sweden (+46)",
    emoji: "🇸🇪",
    code: "SE",
  },
  {
    name: "Switzerland",
    dial_code: "Switzerland (+41)",
    emoji: "🇨🇭",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "Syrian Arab Republic (+963)",
    emoji: "🇸🇾",
    code: "SY",
  },
  {
    name: "Taiwan",
    dial_code: "Taiwan (+886)",
    emoji: "🇹🇼",
    code: "TW",
  },
  {
    name: "Tajikistan",
    dial_code: "Tajikistan (+992)",
    emoji: "🇹🇯",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "Tanzania (+255)",
    emoji: "🇹🇿",
    code: "TZ",
  },
  {
    name: "Thailand",
    dial_code: "Thailand (+66)",
    emoji: "🇹🇭",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    dial_code: "Timor-Leste (+670)",
    emoji: "🇹🇱",
    code: "TL",
  },
  {
    name: "Togo",
    dial_code: "Togo (+228)",
    emoji: "🇹🇬",
    code: "TG",
  },
  {
    name: "Tokelau",
    dial_code: "Tokelau (+690)",
    emoji: "🇹🇰",
    code: "TK",
  },
  {
    name: "Tonga",
    dial_code: "Tonga (+676)",
    emoji: "🇹🇴",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "Trinidad and Tobago (+1868)",
    emoji: "🇹🇹",
    code: "TT",
  },
  {
    name: "Tunisia",
    dial_code: "Tunisia (+216)",
    emoji: "🇹🇳",
    code: "TN",
  },
  {
    name: "Turkey",
    dial_code: "Turkey (+90)",
    emoji: "🇹🇷",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    dial_code: "Turkmenistan (+993)",
    emoji: "🇹🇲",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "Turks and Caicos Islands (+1649)",
    emoji: "🇹🇨",
    code: "TC",
  },
  {
    name: "Tuvalu",
    dial_code: "Tuvalu (+688)",
    emoji: "🇹🇻",
    code: "TV",
  },
  {
    name: "Uganda",
    dial_code: "Uganda (+256)",
    emoji: "🇺🇬",
    code: "UG",
  },
  {
    name: "Ukraine",
    dial_code: "Ukraine (+380)",
    emoji: "🇺🇦",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    dial_code: "United Arab Emirates (+971)",
    emoji: "🇦🇪",
    code: "AE",
  },
  {
    name: "United Kingdom",
    dial_code: "United Kingdom (+44)",
    emoji: "🇬🇧",
    code: "GB",
  },
  {
    name: "United States",
    dial_code: "United States (+1)",
    emoji: "🇺🇸",
    code: "US",
  },
  {
    name: "Uruguay",
    dial_code: "Uruguay (+598)",
    emoji: "🇺🇾",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    dial_code: "Uzbekistan (+998)",
    emoji: "🇺🇿",
    code: "UZ",
  },
  {
    name: "Vanuatu",
    dial_code: "Vanuatu (+678)",
    emoji: "🇻🇺",
    code: "VU",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "Venezuela (+58)",
    emoji: "🇻🇪",
    code: "VE",
  },
  {
    name: "Vietnam",
    dial_code: "Vietnam (+84)",
    emoji: "🇻🇳",
    code: "VN",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "Virgin Islands, British (+1284)",
    emoji: "🇻🇬",
    code: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "Virgin Islands, U.S. (+1340)",
    emoji: "🇻🇮",
    code: "VI",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "Wallis and Futuna (+681)",
    emoji: "🇼🇫",
    code: "WF",
  },
  {
    name: "Yemen",
    dial_code: "Yemen (+967)",
    emoji: "🇾🇪",
    code: "YE",
  },
  {
    name: "Zambia",
    dial_code: "Zambia (+260)",
    emoji: "🇿🇲",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    dial_code: "Zimbabwe (+263)",
    emoji: "🇿🇼",
    code: "ZW",
  },
];
