export const initialChartDataState = {
  activeClients: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  allClients: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  newlyEnrolledClients: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  onAppointment: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  missedAppointment: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  interrupted: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  returned: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  dueForViralLoad: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  adultART: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  childART: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  viralLoadSamples: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  viralLoadResults: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  highViralLoad: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  underCareOfCommunityProgram: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  viralLoadCoverage: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  viralLoadSuppression: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  highViralLoadCascade: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
  waterfall: {
    raw: null,
    processedChartData: [],
    loading: false,
    lineListComplete: true,
  },
}
