export const facilities = [
  {
    "Western Equatoria States": [
      "140th SPLA Batalion PHCU",
      "Affa PHCU",
      "Agyi PHCU",
      "Akpa PHCU",
      "Amadi PHCU",
      "Amaki PHCU",
      "Andari PHCU",
      "Army PHCU",
      "Asanza PHCU",
      "Baakpara PHCU",
      "Bafuka PHCU",
      "Bagidi PHCU",
      "Baguga PHCU",
      "Bahr Grindi PHCU",
      "Baikpa PHCU",
      "Bakiringba PHCU",
      "Bakiwiri PHCU",
      "Bamani PHCU",
      "Bambaraze PHCU",
      "Bambu PHCU",
      "Bandala PHCU",
      "Bandala PHCU (Ezo)",
      "Banduguyo PHCU",
      "Bangangai PHCU",
      "Bangaru PHCU",
      "Bangasu PHCC",
      "Baragu PHCU",
      "Bari PHCU",
      "Bariabande PHCU",
      "Bariguna PHCU",
      "Basanabaru PHCU",
      "Bassan PHCU",
      "Basukangbi PHCC",
      "Bavuru PHCU",
      "Bazumbura PHCU",
      "Bazungua PHCC",
      "Bekenye PHCU",
      "Benzim Foki PHCU",
      "Bereangburu PHCU",
      "Betha Saida ECS PHCC",
      "Bingo PHCU",
      "Birisi PHCU",
      "Bishop Duatuka PHCU",
      "Bitti PHCU",
      "Bodo PHCU",
      "Bogori PHCU",
      "Bongolo PHCC",
      "Buagyi PHCU",
      "Burezigbo PHCU",
      "Chochoro PHCU",
      "Dangu PHCU",
      "Degere PHCU",
      "Diabio PHCU",
      "Diatoro PHCU",
      "Diayanga PHCU",
      "Diko PHCU",
      "Dingapai PHCU",
      "Dingimo PHCU",
      "Domeri PHCU",
      "Don Bosco Clinic PHCC",
      "Doro PHCU",
      "Dorrolilli PHCU",
      "Dosho PHCU",
      "Duatuka PHCU",
      "Duduma PHCU",
      "Dukudu-olo PHCC",
      "Duma PHCU",
      "ECS Good Samaritan PHCC",
      "ECS Masumbu PHCU",
      "Embe PHCU",
      "Ezo PHCC",
      "Ezo Border Point",
      "Ezo Hospital",
      "Gabat PHCU",
      "Gamunakpe PHCU",
      "Gangura PHCC",
      "Garia PHCU",
      "Gbatanzere PHCU",
      "Gira PHCU",
      "Goribalau PHCU",
      "Gulu PHCU",
      "Guruba PHCU",
      "Guruvanza PHCU",
      "Hikpiro PHCU",
      "Ibba PHCC",
      "Ibba Prison PHCU",
      "IDEAS PHCU",
      "Iggi PHCU",
      "Igyi PHCU",
      "Karika PHCU",
      "Kasia PHCU",
      "Kasiko PHCU",
      "Kediba PHCC",
      "Kidi PHCU",
      "Kombi PHCU",
      "Kotobi PHCC",
      "Kozi PHCU",
      "Kpasua PHCU",
      "Kporoloo PHCU",
      "Kulu PHCU",
      "Kulundu PHCU",
      "Kuro PHCU",
      "Kwanga PHCU",
      "Lakamadi PHCC",
      "Lali PHCU",
      "Langua PHCU",
      "Lanyi PHCC",
      "Ledingwa PHCU",
      "Lesi PHCU",
      "Leybolo PHCU",
      "Li Rangu PHCC",
      "Lokoyo PHCU",
      "Longbua PHCU",
      "Lozoh PHCU",
      "Lui HOSPITAL",
      "Luthern Church PHCU",
      "Mabaiku PHCU",
      "Mabema PHCU",
      "Mabenge PHCU",
      "Mabia PHCU",
      "Mabilindi PHCU",
      "Madebe PHCC",
      "Madoro PHCC",
      "Mafuyu PHCU",
      "Magbuka PHCU",
      "Magida PHCU",
      "Magyirii PHCU",
      "Makpandu PHCC",
      "Mambe 1 PHCU",
      "MAMBE T PHCU",
      "Mandi PHCU",
      "Mangbangau PHCU",
      "Mangbondo PHCU",
      "Mangburu PHCU",
      "Manikakare PHCU",
      "Manvugo PHCU",
      "Manzengbi PHCU",
      "Manzinzi PHCU",
      "Mapakuka PHCU",
      "Marangu PHCU",
      "Mariagba PHCU",
      "Maridi HOSPITAL",
      "Maridi Prison PHCU",
      "Maringindo PHCU",
      "Marko PHCU",
      "Maruko PHCU",
      "Masiya PHCU",
      "Masumbu PHCU",
      "Matakurungu PHCU",
      "Matato PHCU",
      "Matoto PHCU",
      "Mbara PHCU",
      "Mbara PHCU",
      "Mboroko PHCU",
      "Meke 2 PHCU",
      "Mekke II PHCC",
      "Mideh PHCC",
      "Minga PHCC",
      "Miriba PHCU",
      "Moba PHCU",
      "Moku PHCU",
      "Momboi PHCU",
      "Moso PHCU",
      "Movo PHCU",
      "Mudubai PHCU",
      "Mundri PHCC",
      "Mupoi PHCC",
      "Mvolo PHCC",
      "N.H.I Yambio PHCC",
      "Naam PHCU",
      "Naandi PHCC",
      "Naangbimo PHCU",
      "Nabaga PHCC",
      "Nabagu I PHCU",
      "Nabagu II PHCU",
      "Nabanga PHCC",
      "Nabaria PHCU",
      "Nabia Pai PHCU",
      "Nabubu PHCU",
      "Nadiagere PHCC",
      "Nagasi PHCU",
      "Nagbaka PHCU",
      "Nagero PHCC",
      "Nakapazi P PHCU",
      "Nakiri PHCU",
      "Nakofo PHCU",
      "Namaiku PHCU",
      "Namama II PHCU",
      "Namama PHCU",
      "Nambia PHCU",
      "Nambia PHCU",
      "NambiaII PHCU",
      "Namutina PHCC",
      "Nangbabe PHCU",
      "Nangbabe1 PHCU",
      "Nangere PHCU",
      "Nangirimo PHCU",
      "Nangongo PHCU",
      "Nangume PHCU",
      "Nanguruza PHCU",
      "Nanzinga PHCU",
      "Napere PHCU",
      "Nasue PHCU",
      "Nayure PHCU",
      "Ndauuro PHCU",
      "Ndavura PHCU",
      "Ndoromo PHCU",
      "Ngamunde PHCC",
      "Ngbambia PHCU",
      "Ngboko PHCU",
      "Ngburusai PHCU",
      "Ngogala PHCU",
      "Ngoni PHCU",
      "Ngonzorono PHCU",
      "Ngunkata PHCU",
      "Nuni PHCU",
      "Nyaka PHCU",
      "Nyasi PHCU",
      "Nzama PHCU",
      "Nzara HOSPITAL",
      "Nzara PHCC",
      "Olo PHCC",
      "Pastor Poul MC PHCU",
      "Ras-Tigi PHCU",
      "Ribodo PHCU",
      "Rii-Bodo PHCU",
      "Rii-Rangu PHCC",
    ],
    "Lakes State": [
      "Abang PHCU",
      "Abarkou PHCU",
      "Abeer PHCU",
      "Abinajok PHCU",
      "Abiriu PHCC",
      "Abuyung PHCU",
      "Achiek PHCU",
      "Acigor PHCU",
      "Adior PHCC",
      "Adir-Dir PHCU",
      "Adol PHCC",
      "Aduel PHCC",
      "Agangrial PHCU",
      "Agany PHCU",
      "Akoljal PHCU",
      "Akot PHCC",
      "Aloor PHCU",
      "Aluak Luak PHCC",
      "Amer PHCU",
      "Ameth Duol PHCU",
      "Amok PHCU",
      "Amongpiny PHCC",
      "Anuol PHCC",
      "Aruau PHCU",
      "Atiaba PHCU",
      "Awac PHCU",
      "Awerial PHCU",
      "Ayai PHCU",
      "Ayai PHCU",
      "Bahr Gel PHCU",
      "Bahrgel PHCU",
      "Bal-Wau PHCU",
      "Bar-Aliap PHCU",
      "Bar-Chol PHCU",
      "Betoi PHCU",
      "Billing PHCU",
      "Bunagok PHCC",
      "Chitchok PHCC",
      "Chitchok PHCC",
      "Coloc-Cok PHCU",
      "Cuei-Adukan PHCU",
      "Cueibet County Hospital",
      "Cueicok PHCC",
      "Deng Nhial PHCU",
      "Deteku PHCU",
      "Dhiau-Kuei PHCU",
      "Diocese of Rumbek PHCC",
      "Dokuru PHCU",
      "Dor PHCU",
      "Duony PHCU",
      "Guba PHCU",
      "Gulmar PHCU",
      "Kalthok PHCU",
      "KAP PHCU",
      "Kiir Mayardit Woman HOSPITAL",
      "kubri William PHCU",
      "Kuelkuec PHCU",
      "Laam PHCU",
      "Lang Matol PHCU",
      "Langdit PHCU",
      "Lekakedu PHCU",
      "Mabor Duang PHCC",
      "Maboric PHCU",
      "Mabui PHCU",
      "Majak-Jier PHCU",
      "Makembele PHCU",
      "Makila PHCU",
      "Makor PHCU",
      "Malek PHCC",
      "Malengok PHCU",
      "Malou Jiec PHCC",
      "Malou Pec PHCC",
      "Malual Bab PHCC",
      "Malueth PHCU",
      "Manai PHCU",
      "Mangang PHCU",
      "Maper 2 PHCU",
      "Maper Centre HOSPITAL",
      "Maper PHCC",
      "Mapuordit HOSPITAL",
      "Mary Ward PHCC",
      "Matangai PHCC",
      "Mathiang Kok PHCU",
      "Mathiangdhiei PHCU",
      "Mayath PHCU",
      "Mayen PHCU",
      "Mayen PHCU",
      "Mayen Thon PHCU",
      "Minkaman PHCC",
      "Morkuec PHCU",
      "Nuktamanga PHCU",
      "Nyang Koot PHCU",
      "Nyang PHCC",
      "Pabur PHCU",
      "Pacong PHCC",
      "Pagang PHCU",
      "Pagarau PHCC",
      "Pagor PHCU",
      "Paloc PHCC",
      "Panawac PHCU",
      "Pandit PHCU",
      "Pandit PHCU",
      "Pandit PHCU",
      "Pankar PHCU",
      "Police PHCC",
      "Police PHCC",
      "Rumbek Central Prison PHCC",
      "Rumbek State HOSPITAL",
      "Shambe PHCU",
      "St. Joseph TB PHCC",
      "St. Josephine Bhakita PHCC",
      "ST. Mary PHCC",
      "St. Mary PHCC",
      "Thonabutkok PHCU",
      "Tiap Tiap PHCU",
      "Tonjo PHCU",
      "Wako PHCU",
      "War-Liet PHCU",
      "Wouwou PHCU",
      "Wulu Gedim PHCU",
      "Wulu PHCC",
      "Wun-rieng PHCU",
      "Yirol County Hospital",
    ],
    "Eastern Equatoria State": [
      "Abara PHCC",
      "Adeba PHCU",
      "Agoro PHCU",
      "AIC Lohutok PHCC",
      "Amee PHCU",
      "Amiru PHCU",
      "Anzara PHCU",
      "Arapi PHCU",
      "Aromo PHCU",
      "Ateda PHCU",
      "Ayii PHCU",
      "Biira PHCC",
      "Bilinya PHCU",
      "Bule PHCU",
      "Bur Mutaram PHCU",
      "Camp Fifteen Military PHCU",
      "Chahare PHCU",
      "Chalamini PHCU",
      "Chawa PHCU",
      "Choroi PHCU",
      "Chorokol PHCU",
      "Chukudum HOSPITAL",
      "Chumakori PHCU",
      "FRAK-SIKA PHCU",
      "Ganzi PHCU",
      "Gilo PHCU",
      "Good Shephard PHCC",
      "Haba PHCU",
      "Haforiere PHCU",
      "Haliba PHCU",
      "Hatire PHCC",
      "Hidonge Ifura PHCU",
      "Hidonge malagit PHCU",
      "Hilieu PHCC",
      "Hiyala PHCC",
      "Huma PHCU",
      "Ibalany PHCU",
      "Ibele PHCU",
      "Ibonni PHCU",
      "Idali PHCU",
      "Ifuto PHCC",
      "Ikwoto PHCC",
      "Ilieu PHCU",
      "Iloli PHCU",
      "IMEDU PHCU",
      "Imedu PHCU",
      "Imehejek PHCC",
      "Imila PHCU",
      "Imilai PHCU",
      "Imokoru PHCU",
      "Imotong PHCC",
      "Imuluha PHCU",
      "Imurok PHCU",
      "Jie PHCU",
      "Kadumakuc PHCU",
      "Kalacha PHCU",
      "Kalisoni PHCU",
      "Kaludo PHCU",
      "Kalupe PHCU",
      "Kapeta PHCU",
      "Kapoeta Civil Hospital",
      "Kapoeta Mission Hospital",
      "Kathac PHCU",
      "Katiko PHCC",
      "Kerepi PHCU",
      "Khormush PHCU",
      "Kibak PHCU",
      "Kibongorok PHCU",
      "Kicenga PHCC",
      "Kidepo PHCU",
      "Kikilai PHCC",
      "Kimotong PHCC",
      "Komiri PHCC",
      "Kudo PHCC",
      "Kujikor PHCU",
      "Kuron PHCC",
      "Lacharok PHCU",
      "Lafon PHCC",
      "Lagii PHCU",
      "Lalanga PHCU",
      "Langaro PHCU",
      "Lawaci PHCU",
      "Lelang PHCU",
      "Lerwa PHCU",
      "Loa Mission PHCC",
      "Lobira PHCU",
      "Lobone PHCC",
      "Lobwaye PHCU",
      "Lodurumo PHCU",
      "Lodwara PHCU",
      "Lofulung PHCU",
      "Lofus PHCU",
      "Logire Hutuk-hinyang PHCU",
      "Logonowati PHCU",
      "Lojiong PHCU",
      "Lokidele PHCU",
      "Lokoges PHCU",
      "Lomarati PHCU",
      "Lomeyen PHCU",
      "Loming PHCU",
      "Lomwoo PHCU",
      "LONGARIO PHCU",
      "Longeleya PHCU",
      "Longiro PHCU",
      "Longonawati PHCU",
      "Longu PHCU",
      "Longwere PHCC",
      "Loolim PHCU",
      "Lopetet PHCU",
      "Lopua PHCU",
      "Lorema PHCC",
      "Lorima PHCU",
      "Loriyok PHCU",
      "LOTIMOR PHCU",
      "Lotome PHCU",
      "Loulang PHCU",
      "Lowoi PHCC",
      "Lowoyakali PHCU",
      "Lwala PHCU",
      "Magwi CDOT PHCC",
      "Magwi PHCC",
      "Maji PHCU",
      "Malaya PHCU",
      "MALNYANG PHCU",
      "Mangalla PHCU",
      "Marie Stopes Torit Centre PHCC",
      "Masindi PHCU",
      "Mogos PHCC",
      "Moli Andru PHCU",
      "Moli Tokuro PHCC",
      "Momoria PHCU",
      "Moruanrengan PHCU",
      "Mossingo PHCU",
      "Moti PHCU",
      "Mugali PHCC",
      "Mura Hatiha PHCU",
      "Mura Lopit PHCU",
      "Mutebwa PHCU",
      "Naakwa PHCC",
      "Nachilagur PHCU",
      "Nachukut PHCU",
      "Nadapal PHCU",
      "Nagishot PHCC",
      "Nak Nak PHCU",
      "Nakabangole PHCU",
      "Nakabangole PHCU",
      "Nakoringole PHCU",
      "Nakware PHCU",
      "NALIEL PHCU",
      "NALINGARO PHCU",
      "Naminitoit PHCU",
      "Naminitoit Prison PHCU",
      "Namonicheck PHCU",
      "NAMORONYANG PHCU",
      "NAMORUPUS PHCU",
      "Nangolet PHCU",
      "Nangoletirae PHCU",
      "Napetait PHCC",
      "NAPOTPOT (Loburi) PHCU",
      "Narus Border Point",
      "Narus CDoT PHCC",
      "Narus PHCC",
      "Nasigigriate PHCU",
      "Naswat PHCU",
      "Nathilani PHCU",
      "Natikai OTP",
      "Natinga PHCU",
      "National Health Insurance PHCC",
      "Nawoyamuria PHCU",
      "Nawoyamuria PHCU",
      "New Site Wodran PHCC",
      "Ngaluma PHCU",
      "Ngatuba PHCU",
      "Ngauro PHCC",
      "Nimule Border Point",
      "Nimule CDOT PHCC",
      "Nimule HOSPITAL",
      "Nimule Isolation",
      "Normeca PHCC",
      "Nyara PHCU",
      "Nyong PHCC",
      "Obbo PHCC",
      "Offi PHCU",
      "Offiri PHCU",
      "Ofiriha Magwi PHCU",
      "Ofiriha PHCU",
      "Oguruny PHCU",
      "Ohila PHCU",
      "Ohiri PHCU",
      "Okorohore PHCU",
      "Olere PHCU",
      "Olianga PHCU",
      "Olikwi PHCU",
      "Omeo PHCU",
      "Ongelet PHCU",
      "Opari PHCC",
      "Oriaju PHCU",
      "Orobe PHCU",
      "Oronyo PHCC",
      "Osito PHCU",
      "OWING KIBUL M. TXC VCT PHCU",
      "Owinykibul PHCC",
      "OWINYKIBUL PHCU",
      "Pachidi/Lwala PHCU",
      "Pageri PHCC",
      "Pajok PHCC",
      "Pajok PHCU",
      "Palotaka PHCU",
      "Paluonganyi PHCU",
      "Palwar PHCU",
      "PARINGA PHCU",
      "PATIBI PHCU",
      "Piobokoi PHCU",
      "Pogee PHCU",
      "Ramula PHCU",
      "Riwoto PHCC",
      "Sacret Heart Kerepi PHCC",
      "SMC/NARUS PHCC",
      "St Theresa Isohe Mission HOSPITAL",
      "Sudenese gospel Mission PHCC",
      "Taar PHCU",
      "Tirangore PHCU",
      "Torit Military Hospital",
      "Torit prison PHCU",
      "Torit State HOSPITAL",
      "Tseretenya PHCU",
      "Tulugi PHCU",
      "Ugwil/Malnyang PHCU",
      "Ukwanya PHCU",
      "Ungebe PHCU",
      "Upuo PHCU",
      "WinyoLwonga PHCU",
      "Wipuboy PHCU",
      "Wokobu PHCU",
    ],
    "Upper Nile State": [
      "Abayok PHCC",
      "Abienyai PHCU",
      "Abukadhra PHCU",
      "Aburoc PHCC",
      "Aburoc PHCU",
      "Achake PHCU",
      "Aderi PHCU",
      "Adodo PHCC",
      "Adong PHCC",
      "Akoka PHCC",
      "Akurwa PHCU",
      "Al Gabat PHCU",
      "Alaka PHCU",
      "Alaki PHCU",
      "Alel PHCU",
      "Assossa PHCU",
      "Athidwoi PHCC",
      "Athidwoi PHCU",
      "Aweth PHCC",
      "Ayat PHCU",
      "Bai-chan PHCU",
      "Baliet PHCC",
      "Bam PHCU",
      "Banashowa PHCU",
      "Banashowa PHCU",
      "Banjang PHCU",
      "Barmach PHCU",
      "Belwang PHCU",
      "Benamayo PHCC",
      "Bienythiang PHCU",
      "Bimbim PHCU",
      "Bol PHCU",
      "Bougaya PHCU",
      "Bunj HOSPITAL",
      "Bunj RI PHCC",
      "Bushara PHCU",
      "Catholic Church PHCC",
      "Chemmedi PHCC",
      "Chot Lual PHCU",
      "Chutbora PHCC",
      "Dajok PHCC",
      "Dangaji PHCU",
      "Delal Ajak PHCU",
      "Detang PHCU",
      "Detwok PHCU",
      "Dhekdhek PHCU",
      "Dhourding PHCU",
      "Diingthama PHCC",
      "Dingkar PHCU",
      "Doliephill PHCU",
      "Doma PHCU",
      "Doro Extension PHCU",
      "Doro PHCC",
      "Dugdug PHCU",
      "Dura PHCU",
      "ECS PHCC",
      "ECS PHCU",
      "Gaireng PHCU",
      "Galdora PHCC",
      "Gandrassa PHCC",
      "Gasm Allah PHCU",
      "Gellachol PHCU",
      "Gentil PHCC",
      "Gerger PHCC",
      "Global Health PHCC",
      "Globany PHCU",
      "Goldora IDP PHCC",
      "Gollo PHCU",
      "Guelguk PHCC",
      "Gurnyang PHCU",
      "Gusfami PHCU",
      "Hai Ismael Hamed PHCU",
      "Homkor PHCU",
      "Jalhak PHCC",
      "Jalhak PHCU",
      "Jamam PHCU",
      "Jekow PHCU",
      "Jerbana PHCC",
      "Jikmir PHCC",
      "Jinkuatta PHCU",
      "Jongok PHCU",
      "Jotome PHCU",
      "Jurbenak PHCU",
      "Kaka PHCC",
      "Kaya PHCU",
      "Khor Tombak PHCU",
      "Kiechkuon PHCC",
      "Kierwan PHCU",
      "Kierwanding PHCU",
      "Kigile PHCU",
      "Kilo 15 PHCU",
      "Kilo 5 PHCU",
      "Kitgwang PHCU",
      "Kitgwang PHCC",
      "Koat PHCU",
      "Kodok Hospital",
      "Kolang PHCU",
      "Kuerenge-ke PHCU",
      "Kuich PHCC",
      "Kwek PHCU",
      "Latbier PHCU",
      "Lelo PHCU",
      "Liang PHCU",
      "Loier PHCU",
      "Lonylok PHCU",
      "Luakat PHCU",
      "Lual Yak PHCU",
      "Luek PHCU",
      "Lul West PHCU",
      "Mading PHCC",
      "Maiwut PHCC",
      "Majiok PHCU",
      "Makal PHCU",
      "Malakal PoC IOM Clinic",
      "Malakal Teaching HOSPITAL",
      "Mallo PHCU",
      "Malow PHCU",
      "Malual PHCU",
      "Manam PHCU",
      "Mathiang PHCC",
      "Mayak PHCU",
      "Melut Civil HOSPITAL",
      "Molbuk PHCU",
      "MSF - HOLLAND HOSPITAL",
      "MSF Clinic PHCC",
      "N.H.I PHCC",
      "N.H.I PHCC",
      "Nakdiar PHCU",
      "Nasir HOSPITAL",
      "National Insuarence PHCC",
      "New Guffa PHCU",
      "Nilla PHCU",
      "Noon PHCU",
      "Nyangore PHCU",
      "Nyetok PHCU",
      "Nyibodo PHCU",
      "Nyiliech PHCU",
      "Nyiluak PHCC",
      "Obei PHCC",
      "Obel PHCC",
      "Obud PHCU",
      "Ogon PHCU",
      "Ogot IPD PHCU",
      "Omar PHCU",
      "Omdulus PHCU",
      "Ommire PHCU",
      "Orinyi PHCC",
      "Otego PHCU",
      "Oweci PHCC",
      "Pabo PHCU",
      "Pagak PHCC",
      "Pakang PHCU",
      "Pakwar PHCU",
      "Paloch PHCC",
      "Pamac PHCU",
      "Panomdit PHCU",
      "Papwojo PHCU",
      "Pariak PHCU",
      "Paroc PHCU",
      "Pen PHCU",
      "Pinythor PHCU",
      "POC clininc IDPs PHCC",
      "POC Hospital IDPs HOSPITAL",
      "Poumki PHCU",
      "Renk",
      "Renk Border Point",
      "Renk HOSPITAL",
      "Renk Military HOSPITAL",
      "Riangnum PHCU",
      "Rirnyang PHCU",
      "Roam PHCU",
      "Rom PHCC",
      "Rom PHCU",
      "Romale PHCU",
      "Rup Board PHCC",
      "Shatta PHCU",
      "SIM Missionary Hospital",
      "Thak PHCU",
      "Thorgwang PHCC",
      "Thorgwang PHCU",
      "Thougji PHCU",
      "Tolar PHCU",
      "Tonga PHCC",
      "Torkiel PHCU",
      "Torpuot PHCU",
      "Turuw PHCU",
      "Ugier PHCU",
      "Ulang PHCC",
      "Uleng PHCU",
      "Wadakona PHCC",
      "Wanamum PHCU",
      "Wanding PHCU",
      "Warajwok PHCU",
      "Warweng PHCU",
      "Watber PHCC",
      "Wau Shilluk PHCU",
      "Wichlita PHCU",
      "Wonthou PHCC",
      "Wudier PHCU",
      "Wunatem C PHCC",
      "Wunbut PHCU",
      "Wunkir PHCU",
      "Ying PHCU",
      "Yomding PHCC",
      "Yusuf Batil PHCC",
      "Yusuf Batil PHCU",
    ],
    "Central Equatoria State": [
      "Abegi PHCU",
      "ADRA Youth Centre PHCU",
      "African Inland Church PHCC",
      "African Inland Church PHCC",
      "Agonyakiri PHCU",
      "Ajio PHCU",
      "Ajira PHCU",
      "Al Amin HOSPITAL",
      "Al Amin Nursing Home HOSPITAL",
      "Aloto Rural PHCU",
      "Angebi PHCU",
      "Aru Junction PHCU",
      "Aspen Medical International HOSPITAL",
      "Atiit PHCU",
      "Aworo/Aboroto PHCC",
      "Bamurye PHCU",
      "Bandame PHCU",
      "Bekat PHCU",
      "Belpham Military PHCC",
      "Bereka PHCU",
      "Bilingi PHCU",
      "Bilinyang PHCU",
      "Bori PHCC",
      "Boro Boro PHCU",
      "Buko PHCU",
      "Bungu PHCU",
      "Bura PHCU",
      "Bura PHCU",
      "ChinaFriendship HOSPITAL",
      "Comboni PHCU",
      "Da Geneisis Hospital",
      "Dari PHCU",
      "Dari PHCU",
      "Digala PHCC",
      "Dimo One PHCU",
      "Dokuni PHCU",
      "Don Bosco PHCC",
      "EB Clinic",
      "El-Sabah Children HOSPITAL",
      "EPC PHCC",
      "Festo Maternity HOSPITAL",
      "Friendship Medical HOSPITAL",
      "Gaderu PHCC",
      "Ganji PHCC",
      "Gemeiza PHCU",
      "Gendressa PHCC",
      "Geri PHCU",
      "Ghabat PHCC",
      "Gimora PHCU",
      "Gimunu PHCU",
      "Ginyabio PHCU",
      "Goja PHCU",
      "Goli PHCU",
      "Gondokoro PHCU",
      "Good Sephard PHCC",
      "Gorom PHCC",
      "Gudele Block 4 PHCU",
      "Gudele Surgical Home PHCU",
      "Gudele Surgical Home Private HOSPITAL",
      "Gumbo PHCC",
      "Gurei PHCC",
      "Gurujo PHCU",
      "Gurulotogu PHCU",
      "Gwulukuk PHCU",
      "Hai Jebel PHCU",
      "Hamia PHCC",
      "IDU",
      "Ilyangiri PHCU",
      "International HOSPITAL",
      "Jalimo PHCC",
      "Jalite Gikokue PHCU",
      "Jamara PHCC",
      "Jobem PHCU",
      "Jokari PHCU",
      "Jombu PHCU",
      "Jondale PHCU",
      "Jondoki PHCC",
      "Jonkok PHCU",
      "Juba Central Prison PHCC",
      "Juba Int Airport",
      "Juba Medical Complex HOSPITAL",
      "Juba Military HOSPITAL",
      "Juba POC",
      "Juba Police PHCC",
      "Juba Prison PHCC",
      "Juba Teaching HOSPITAL",
      "Kagelu PHCU",
      "Kagwada PHCU",
      "Kajiko PHCU",
      "Kajo Keji Civil Hospital",
      "Kala PHCU",
      "Kangai PHCC",
      "Kansuk PHCC",
      "Karpeto PHCU",
      "Kasurak PHCU",
      "Katigiri PHCC",
      "Kator PHCC",
      "Kaya PHCC",
      "Kaya PHCC",
      "Kendila PHCU",
      "Kenyi PHCU",
      "Kera PHCC",
      "Kerwa PHCU",
      "Khor Romula/Jenduru PHCU",
      "Khorwalliang PHCC",
      "Kigwo PHCU",
      "Kimba PHCU",
      "Kimu PHCC",
      "Kinyiba PHCC",
      "Kinyiba PHCU",
      "Kiri PHCU",
      "Kirikwa PHCU",
      "Kirot nyumbo PHCU",
      "Kiu/Kiyu PHCU",
      "Komoi PHCU",
      "Kowori PHCU",
      "Koyoki PHCC",
      "Krot Nyumbo PHCU",
      "Kubi PHCU",
      "Kuda PHCC",
      "Kuda PHCU",
      "Kudaji PHCU",
      "Kuli Papa PHCU",
      "Kundru PHCU",
      "Kupera PHCU",
      "Kutali PHCU",
      "Kutuk na woko PHCU",
      "Kworijik PHCU",
      "Kwornyang PHCU",
      "Lainya PHCC",
      "Langi PHCU",
      "Lasu PHCC",
      "Latta PHCU",
      "Leikor PHCU",
      "Lengi PHCU",
      "Libogo PHCU",
      "Ligi PHCU",
      "Limbe PHCC",
      "Limi PHCU",
      "Limuro PHCU",
      "Lire PHCC",
      "Lirya PHCC",
      "Litoba PHCU",
      "Liwolo Missionaries Hospital",
      "Lobonok PHCC",
      "Logili PHCU",
      "Logo PHCU",
      "Logobero PHCU",
      "Logotibari PHCU",
      "Logu PHCU",
      "Logwerle PHCU",
      "Logwili PHCU",
      "Lojora PHCU",
      "Loka Orphanage PHCU",
      "Loka Round PHCU",
      "Loka West PHCU",
      "Lokiliri PHCC",
      "Lokweni PHCU",
      "Lologo PHCC",
      "Lomega PHCU",
      "Lomilikin PHCU",
      "Lomin PHCC",
      "Longira PHCU",
      "Lora PHCC",
      "Lora PHCU",
      "Lori PHCU",
      "Loro PHCU",
      "Lorumba PHCU",
      "Lotemba PHCU",
      "Lowirja PHCU",
      "Lujulo PHCU",
      "Luri rokwe PHCU",
      "Luri-Somba PHCU",
      "Lutheran PHCC",
      "Lwoki PHCU",
      "Madikolok PHCU",
      "Mading PHCU",
      "Mahad PHCU",
      "Makamagor PHCU",
      "Makido PHCU",
      "Malakia PHCC",
      "Malakia PHCU",
      "Mangalla PHCC",
      "Mangalotore PHCU",
      "Mangaten PHCU",
      "Mangele PHCU",
      "Mangkaro PHCU",
      "Mankaro PHCU",
      "Mapako PHCU",
      "Martha PHCC",
      "Matika PHCU",
      "Mawuna HOSPITAL",
      "Medicare HOSPITAL",
      "Mengele/Mankole PHCU",
      "Mere PHCU",
      "Mereguga PHCU",
      "Mijiki PHCU",
      "Mina PHCU",
      "Minyori PHCU",
      "Mirikio PHCC",
      "Mobil PHCU",
      "Mogiri PHCU",
      "Mogiri/Jobur PHCC",
      "Moijo PHCU",
      "Moje PHCU",
      "Molosuk PHCU",
      "Mondi PHCU",
      "Mondikolok Missionary PHCC",
      "Mondikolok PHCU",
      "Mondikolok PHCU",
      "Mongo PHCU",
      "Monoji PHCU",
      "Moridi PHCU",
      "Morobo Hospital",
      "Morobo PHCC",
      "Morsack PHCU",
      "Morsak PHCC",
      "Mugiri PHCU",
      "Mugwo PHCC",
      "Mundari Bura PHCC",
      "Muni PHCC",
      "Munuki PHCC",
      "Nesitu PHCU",
      "New Site PHCC",
      "Ngangalla PHCU",
      "Ngulere PHCU",
      "Nyakuron PHCC",
      "Nyamini PHCU",
      "Nyanga PHCU",
      "Nyarjuw PHCU",
      "Nyerjebi PHCU",
      "Nyikabur PHCU",
      "Nyori PHCU",
      "Nyori PHCU",
      "Nyoro PHCU",
      "Nyuwa PHCU",
      "Ombasi PHCC",
      "Orphanage PHCU",
      "Pagara PHCU",
      "Pager PHCC",
      "Pakula PHCU",
      "Panyume PHCU",
      "Payawa PHCU",
      "Peace HOSPITAL",
      "Peiti PHCC",
      "Peri PHCU",
      "Pirisa PHCU",
      "Rajaf East PHCC",
      "Rejaf West PHCC",
      "Rijong PHCC",
      "Rodo PHCU",
      "Rodoba PHCU",
      "Roja PHCU",
      "Rokon Centre PHCU",
      "Rokon PHCC",
      "Romogi PHCU",
      "Roronyo PHCC",
      "Rubeke PHCU",
      "Rungetta PHCU",
      "Rwonyi PHCU",
      "Sacred Heart PHCC",
      "Saregoro PHCU",
      "SDA PHCC",
      "Senema PHCU",
      "Sera Jale PHCU",
      "Sereng PHCU",
      "Sermon PHCU",
      "Sirimon PHCU",
      "Soka PHCU",
      "Sokare PHCU",
      "St Bakhita PHCC",
      "St Luke PHCC",
      "St.Kizito PHCC",
      "Sun Shine HOSPITAL",
      "Sure PHCU",
      "Tali PHCC",
      "Terekeka PHCC",
      "Three Angle PHCC",
      "Tijor Centre PHCC",
      "Tirye PHCU",
      "Toko-Ko-Tulu PHCU",
      "Tombek PHCC",
      "Tore PHCC",
      "Tukoro PHCU",
      "Tulyang PHCU",
      "Undukori PHCU",
      "Usratuna PHCC",
      "Victoria Medical HOSPITAL",
      "Wadupe PHCU",
      "Walawalang PHCU",
      "Wanyang PHCU",
      "Way Station PHCU",
      "Wonduruba PHCC",
      "Wudabi PHCU",
      "Wudu Bori PHCU",
      "Wuji PHCU",
      "Wujugani PHCU",
      "Wurta PHCU",
      "Yapa PHCU",
      "Yaribe PHCU",
      "Yebisak PHCU",
      "Yei Civil Hospital",
      "Yei Isolation",
      "Yondoru PHCU",
      "Yondu PHCU",
      "Yugufe PHCU",
    ],
    "Warrap State": [
      "Abeyok PHCU",
      "Agei PHCU",
      "Aguka PHCU",
      "Ajak Kuach PHCC",
      "Ajiep PHCU",
      "Ajogo PHCU",
      "Ajong PHCU",
      "Akak PHCC",
      "Akier PHCU",
      "Akoc PHCC",
      "Akon PHCC",
      "Akop PHCC",
      "Akortong PHCU",
      "Akurbiok PHCU",
      "Alabek PHCC",
      "Alek PHCC",
      "Aliek PHCC",
      "Ameeth PHCU",
      "Ananatak PHCU",
      "Angernger PHCU",
      "Angui PHCU",
      "Anguoth PHCU",
      "Anyiel Cuar PHCU",
      "Anyiel Kuac PHCC",
      "Aporlang PHCU",
      "Ariang PHCU",
      "Athieng-Pool PHCU",
      "Atuk Kuel PHCU",
      "Aweng PHCC",
      "Awul PHCC",
      "Awut-Wut PHCU",
      "Ayien Amuol PHCU",
      "Badha Alueth PHCU",
      "Bador Luit PHCU",
      "Biem Khat PHCU",
      "Biir Giik PHCU",
      "Bulyom PHCU",
      "Dhiau Agal PHCU",
      "Fareksika PHCU",
      "Gogrial PHCC",
      "Gor Ayak PHCU",
      "Indeed Truth PHCC",
      "Jak PHCU",
      "Kacbek PHCU",
      "Kacuat PHCU",
      "Keet PHCU",
      "Kirrik PHCU",
      "Kuajok State HOSPITAL",
      "Kuelcuk PHCU",
      "Lietnhom DTC PHCC",
      "Ludabot PHCC",
      "Luonyaker PHCC",
      "Lurchuk PHCU",
      "Mabil Yow PHCU",
      "Mabior Kot PHCU",
      "Mabior Tiit PHCU",
      "Mabior yar PHCU",
      "Madau PHCU",
      "Mading Luit PHCU",
      "Magai PHCU",
      "Magak PHCC",
      "Magok Ateny PHCU",
      "Majak Pagai PHCC",
      "Majakbol PHCU",
      "Majak-Nyuom PHCU",
      "Majok Thany PHCU",
      "Majook Noon PHCC",
      "Makuac PHCU",
      "Maliai PHCU",
      "Malou-Hol PHCU",
      "Malual Agaak (Long) PHCU",
      "Malual Muok PHCU",
      "Malualmonyjoc PHCU",
      "Maluil Ajak PHCU",
      "Mamiir Luit PHCC",
      "Mangol PHCU",
      "Manyang-ngok PHCC",
      "Manyiel-Thonny PHCU",
      "Mapara PHCU",
      "Maper Centre PHCC",
      "Marial Guot Juur PHCC",
      "Marial Lou HOSPITAL",
      "Marial Maper PHCC",
      "Marol Anyuang PHCU",
      "Matiel PHCU",
      "Mayen Abun PHCC",
      "Mayen Ador PHCU",
      "Mayen Gumel PHCC",
      "Mayen-Rual PHCU",
      "Mayom Chol Luk PHCU",
      "Mayom Chol PHCU",
      "Mayom-Bioung PHCU",
      "Molbang PHCU",
      "Mother Theresa General HOSPITAL",
      "Ngapagok PHCC",
      "Nyokthiang PHCU",
      "Pagai Anyuon PHCC",
      "Pagakdit PHCU",
      "Pagol PHCU",
      "Pajokbeek PHCU",
      "Pakor PHCU",
      "Palal PHCU",
      "Paliang PHCU",
      "Pan Ameth PHCU",
      "Panabei Awutdeng PHCU",
      "Panacier PHCU",
      "Panakdit PHCU",
      "Panbai Liangarol PHCU",
      "Pandit Liangarol PHCU",
      "Pankot PHCU",
      "Pankuel Thon PHCU",
      "Panlang Noon PHCU",
      "Panliet PHCU",
      "Pan-Nyok PHCC",
      "Pawel PHCU",
      "Paweng PHCC",
      "Peeth PHCU",
      "Pinydit PHCU",
      "Prison PHCC",
      "Riangagany PHCU",
      "Rualbet PHCU",
      "Rumabuth PHCC",
      "Rumabuth PHCC",
      "Rumakeen PHCU",
      "Ruot PHCU",
      "Thiet PHCC",
      "Thurnyior PHCU",
      "Tiit Noon PHCU",
      "Titchok PHCU",
      "Toch Chel PHCU",
      "Toch Noon PHCC",
      "Tonj Don Bosco TB unit",
      "Tonj HOSPITAL",
      "Tuele PHCC",
      "Turalei PHCC",
      "Wanh Alel PHCU",
      "Warrap PHCC",
      "Wuncuai PHCU",
      "Wuncuei Cuar PHCC",
      "Wunlit PHCU",
      "Wunrok PHCC",
      "Wunthilik PHCU",
      "Yiik Adoor PHCU",
      "Yiik Thon PHCC",
    ],
    "Ruweng Administrative Area": [
      "Abiemnom PHCC",
      "Ajoungthok PHCU",
      "Akot PHCU",
      "Awar Piny4 PHCU",
      "Awarpiny PHCU",
      "Bangbang PHCU",
      "Biu PHCC",
      "Bongki PHCU",
      "Gumriak PHCU",
      "Hakima Yacoub PHCC",
      "Hope health Center-Pamir",
      "Jamjang PHCC",
      "Jaw PHCU",
      "Kong PHCU",
      "Magok PHCU",
      "Managuer PHCU",
      "Manajoga PHCU",
      "Manajoga PHCU",
      "Ming PHCU",
      "Nile Ganga PHCC",
      "Nyiel PHCC",
      "Pamiir PHCC",
      "Panyang PHCC",
      "Pariang HOSPITAL",
      "Pathiang PHCU",
      "Pathiew PHCU",
      "Toor/N yokrial PHCU",
      "Wangkuat PHCC",
      "Wunkur PHCU",
      "Yida Center A PHCC",
      "Yida Centre A PHCC",
      "Yida MSF HOSPITAL",
    ],
    "Northern Bahr El Ghazal State": [
      "Abyei Chok PHCU",
      "Achana PHCU",
      "Achana PHCU",
      "Adoor PHCU",
      "Aguat PHCU",
      "Aguat PHCU",
      "Ajak Wol PHCU",
      "Ajok PHCU",
      "Akac PHCC",
      "Akuak Malual PHCU",
      "Akuang Aroual PHCU",
      "Akuang Koc PHCU",
      "Akuang Koc PHCU",
      "Akuangkar PHCU",
      "Akuem PHCC",
      "Alang PHCU",
      "Alok PHCU",
      "Aluel Achot PHCU",
      "Aluel Achot PHCU",
      "Aluel PHCU",
      "Alueth PHCU",
      "Amacrool PHCU",
      "Amatnyang PHCU",
      "Amatnyang PHCU",
      "Amential PHCU",
      "Ameth Akok PHCU",
      "Ameth Akok PHCU",
      "Amethgolduang PHCU",
      "Amothic PHCU",
      "Amothic PHCU",
      "Angol PHCU",
      "Angol PHCU",
      "Angon Lek PHCU",
      "Angon Lek PHCU",
      "Anyuopjang PHCU",
      "Anyuopjang PHCU",
      "Arieth PHCU",
      "Aroyo DTC PHCC",
      "Atuet PHCU",
      "Awada PHCC",
      "Aweil Civil HOSPITAL",
      "Awulic PHCU",
      "Baach PHCU",
      "Bakou PHCU",
      "Bar Mayen PHCC",
      "Bau PHCU",
      "Chalek PHCU",
      "Chamanguoi PHCU",
      "Chelcou PHCC",
      "Chelcou PHCC",
      "Cuomator PHCU",
      "Dakjim PHCU",
      "Gabat PHCC",
      "Gok Machar PHCC",
      "Goldhim TB PHCC",
      "Gor Ayen PHCU",
      "Guangnou PHCU",
      "Guangnou PHCU",
      "Jaac PPF PHCU",
      "Jal Awan PHCU",
      "Jelwan PHCU",
      "Joor Gaar PHCU",
      "Jurbeech PHCU",
      "Kajik PHCU",
      "Kangkuot PHCU",
      "Kiir adem PHCU",
      "Kiirkakbek PHCU",
      "Kuom PHCU",
      "Kuom PHCU",
      "Lieth PHCC",
      "Light House Medical Center",
      "Lueth Lual PHCU",
      "Lueth Ngor PHCU",
      "Lulic PHCU",
      "Mabil PHCC",
      "Mabior Anguei PHCU",
      "Mabior Nyang PHCU",
      "Mabiorkuot PHCU",
      "Mabiorwundiing PHCU",
      "Mabok Akot PHCU",
      "Mabok Tong PHCU",
      "Machar Adhot PHCU",
      "Macharluong PHCU",
      "Madhol PHCU",
      "Madhol PHCU",
      "Maduany PHCU",
      "Magar PHCU",
      "Majak Bai PHCC",
      "Majak Bol PHCU",
      "Majak Kar PHCC",
      "Majakgoi PHCU",
      "Majangai PHCU",
      "Majok Yith Thiou PHCU",
      "Majok-Akeen PHCU",
      "Majook Adim PHCU",
      "Majook Dengdit PHCU",
      "Majook Dengdit PHCU",
      "Maker Anei PHCU",
      "Maker PHCU",
      "Maker PHCU",
      "Makeranei PHCU",
      "Makuac Akech PHCU",
      "Makuei Alel PHCU",
      "Makuoc PHCU",
      "Makuoc PHCU",
      "Malek Bol PHCU",
      "Malek Mir PHCU",
      "Malekalel PHCU",
      "Malith Alekyai PHCU",
      "Malou mou PHCU",
      "Malual Baai PHCC",
      "Malual Deng Aruom PHCU",
      "Malual Dit PHCU",
      "Malual Kuel PHCU",
      "Malual Kuel PHCU",
      "Malualkon PHCC",
      "Malualkon PHCC",
      "Malual-Kuel PHCU",
      "Maluil Akot PHCU",
      "Mangar Tong PHCU",
      "Mangok PHCU",
      "Manyel PHCU",
      "Manyiel Akok PHCU",
      "Maper Ngok PHCU",
      "Maper PHCU",
      "Mareng Akok PHCU",
      "Marial Bai DTC PHCC",
      "Marial Bai DTC PHCC",
      "Marol buol PHCU",
      "Marol Deng Geng PHCU",
      "Marol Madhan PHCU",
      "Marolajuong PHCU",
      "Marolduliit PHCU",
      "Matuic PHCU",
      "Mayen Ulem PHCU",
      "Mayenadhot PHCU",
      "Mayom Adhal PHCU",
      "Mayom Akuang Rel PHCC",
      "Mayom Akuang Rel PHCC",
      "Mayom Lach PHCC",
      "Mayom Wel PHCU",
      "Mony PHCU",
      "Nyalath PHCU",
      "Nyamlel PHCC",
      "Nyamlel PHCC",
      "Nyien Alel PHCU",
      "Nyieth PHCU",
      "Nyieth PHCU",
      "Nyinbouli PHCC",
      "Nyinbouli PHCC",
      "Omdurman PHCC",
      "Pagai PHCU",
      "Pamat PHCU",
      "Panadhot PHCU",
      "Panjap PHCU",
      "Panthou DTC PHCC",
      "Pantit PHCU",
      "Pantit PHCU",
      "Peth PHCU",
      "Peth PHCU",
      "Peth PHCU",
      "Raingmal PHCU",
      "Rial Diit PHCC",
      "Riangaker PHCU",
      "Riangaketh PHCU",
      "Riangangon PHCU",
      "Roingut PHCU",
      "Rualngol PHCU",
      "Rum Aker PHCU",
      "Rumading PHCU",
      "Rumamoth PHCU",
      "Rumrol PHCU",
      "Rumtiit PHCU",
      "Rumwel PHCU",
      "Rumwet Kor PHCU",
      "Tiar-aleit PHCU",
      "Tit Chok PHCC",
      "Udhum DTC PHCC",
      "Umora PHCU",
      "Warapei PHCC",
      "Warawar PHCU",
      "Warchuei PHCU",
      "Wardong PHCU",
      "Wargeng PHCU",
      "Warkot PHCU",
      "Warlang PHCU",
      "Wathmouk PHCU",
      "Wathok PHCU",
      "Wedweil PHCC",
      "Wedweil PHCC",
      "Wonyjok PHCC",
      "Wuncum PHCU",
      "Wungiir PHCU",
      "Wungiir PHCU",
      "Wunlang PHCU",
      "Yargot PHCU",
    ],
    "Western Bahr El Ghazal State": [
      "Abou PHCU",
      "Abul PHCU",
      "Abushaka PHCU",
      "Achong Chong PHCC",
      "Achot PHCU",
      "Adet PHCU",
      "Ajugo PHCU",
      "Akonbet PHCU",
      "Akrok PHCU",
      "Alelchok PHCU",
      "Alelthony PHCU",
      "Aljazeira PHCC",
      "Apoch PHCU",
      "Atido PHCU",
      "Awany PHCU",
      "Ayo PHCC",
      "Ayom PHCU",
      "Bagari Jedid PHCC",
      "Bagari Jedid PHCU",
      "Barakol PHCU",
      "Bartio PHCU",
      "Barurud PHCU",
      "Baryar PHCU",
      "Bazia Jedid PHCC",
      "Berber PHCU",
      "Besellia PHCC",
      "Boro Medina PHCC",
      "Bringi PHCU",
      "Bussere PHCC",
      "Canning Factory PHCU",
      "Chono PHCU",
      "Daniel Comboni HOSPITAL",
      "Deim Zubeir PHCC",
      "Deimjallab PHCU",
      "Deleba PHCU",
      "Dhekou PHCU",
      "East Bank PHCC",
      "Farajala PHCU",
      "Gessboro PHCU",
      "Gette PHCU",
      "Giatan PHCU",
      "Gumel PHCU",
      "Hai Bafra PHCU",
      "Hai Dinka PHCC",
      "Jebel Kheir PHCC",
      "Kaabi PHCU",
      "Kangi PHCC",
      "Kanyango PHCU",
      "Kapara PHCU",
      "Katta PHCU",
      "Khor Jamus PHCU",
      "Khorghana PHCU",
      "Khorhajar PHCU",
      "Kpaila/Bazia PHCC",
      "Kuajena PHCC",
      "Kuru PHCC",
      "Lokoloko PHCC",
      "Mabior Abiem PHCU",
      "Mabor Abun PHCU",
      "Maju PHCU",
      "Maluil PHCU",
      "Mamoi PHCU",
      "Manamba B PHCU",
      "Mangayat PHCU",
      "Manyang PHCU",
      "Mapel PHCC",
      "Marakas Jerau PHCC",
      "Maranya PHCU",
      "Marial Ajieth PHCU",
      "Marial Bai PHCC",
      "Mary Help HOSPITAL",
      "Mayonga A PHCC",
      "Mbili PHCU",
      "Mboro PHCU",
      "Medil PHCU",
      "Menamba PHCU",
      "MMM Healing PHCC",
      "Muktah PHCC",
      "Naivasha PHCC",
      "Natabu PHCU",
      "National Leprosy PHCC",
      "Ndaku PHCU",
      "New Site PHCC",
      "Ngisa PHCU",
      "Ngodakala PHCC",
      "Ngohalima A PHCU",
      "Ngohalima B PHCU",
      "Ngoku PHCU",
      "Ngoku PHCU",
      "Ngolingbo PHCU",
      "Ngongba PHCU",
      "Nyinakok PHCU",
      "Police PHCU",
      "Raja HOSPITAL",
      "Rihan Fei PHCU",
      "RocRoc Dong PHCU",
      "Sopo PHCU",
      "Taban PHCU",
      "Tharkueng PHCC",
      "Thillic PHCU",
      "Timsah PHCC",
      "Tirga PHCU",
      "Udici PHCC",
      "Wadalel PHCU",
      "Warrieth PHCU",
      "Wau Airport",
      "Wau Military HOSPITAL",
      "Wau Police PHCC",
      "Wau Prison PHCU",
      "Wau Sika Hadid PHCC",
      "Wau Teaching HOSPITAL",
      "Wau Wild Life PHCU",
    ],
    "Unity State": [
      "Adok PHCC",
      "Bentiu PoC, MSF",
      "Bentiu POC, Sector 1 Clinic IOM",
      "Bentiu POC, Sector 2 World Relief PHCC",
      "Bentiu POC, Sector 4 IRC Clinic",
      "Bentiu POC, Sector 5 Clinic World Relief",
      "Bentiu Sector 5",
      "Bentiu State HOSPITAL",
      "Bhor PHCU",
      "Bieh PHCU",
      "Biel Bar PHCU",
      "Bielchier PHCU",
      "Bil PHCU",
      "Bith PHCU",
      "Boaw PHCC",
      "Bou PHCU",
      "Bouth PHCU",
      "Budaang PHCU",
      "Buoth PHCU",
      "Chol Yiel PHCU",
      "Chuk PHCU",
      "Chuoke PHCU",
      "Dablual PHCU",
      "Dekom PHCU",
      "Dera PHCU",
      "Dhor Manyang PHCU",
      "Dhor Manyang PHCU",
      "Dindin PHCU",
      "Dingding PHCU",
      "Duar PHCU",
      "Duong PHCC",
      "Gandor PHCU",
      "Gany PHCU",
      "Ganyiel PHCC",
      "Guat PHCU",
      "Guit PHCC",
      "HAAKUOR PHCU",
      "Haykur PHCU",
      "Jaak PHCU",
      "Jaguar PHCU",
      "Janglou PHCU",
      "Jany Low PHCU",
      "Jieliw PHCU",
      "Juong PHCU",
      "Kaljak PHCC",
      "Kanhnhial PHCU",
      "Kanynhial PHCU",
      "Kedat PHCU",
      "Koch PHCC",
      "Koithiey PHCU",
      "Kol PHCU",
      "Kuach PHCC",
      "Kuerguini PHCU",
      "Kueryiek PHCU",
      "Kuok PHCU",
      "Laidit PHCU",
      "Lanleer PHCU",
      "Leah PHCU",
      "Leer PHCU",
      "Lual PHCU",
      "Luom PHCU",
      "Maal PHCU",
      "Machar PHCU",
      "Madol PHCU",
      "Makur PHCU",
      "Malkuer PHCU",
      "Maluak PHCU",
      "Maluok PHCU",
      "Manga PHCU",
      "Mankien PHCC",
      "Mayendit PHCC",
      "Mayom PHCC",
      "Mayom PHCU",
      "Mayom PHCU",
      "Merlsland PHCU",
      "Mirmir PHCC",
      "Morgok PHCU",
      "MSF HOSPITAL (Bentiu)",
      "Ngong PHCU",
      "Ngop PHCU",
      "Nhialdiu PHCC",
      "Niemni PHCC",
      "Nile Gangah PHCC",
      "Nor Bor PHCU",
      "Nyadong PHCU",
      "Nyal PHCC",
      "Nyathoar PHCU",
      "P.H.Care Unit PHCU",
      "PAAK PHCU",
      "Pabar PHCU",
      "Pabuong PHCU",
      "Pachak PHCU",
      "Pachar PHCU",
      "Pacienjok PHCC",
      "Padeah PHCU",
      "Padieng PHCU",
      "Pakur PHCU",
      "Panyijiar PHCC",
      "Pathiel PHCU",
      "Patit PHCC",
      "Petpet PHCU",
      "Pilieny PHCU",
      "Pouloul PHCU",
      "Pub PHCU",
      "Reang PHCC",
      "Riah PHCU",
      "Rier PHCU",
      "Ruadhnyibol PHCU",
      "Rubkona Care PHCC",
      "Rubkona Military HOSPITAL",
      "Rubkuay PHCC",
      "Rubkuay PHCC",
      "Rubnor PHCU",
      "Rupchay PHCU",
      "Sector3 IOM PHCC",
      "Thakker PHCU",
      "Thoan PHCU",
      "Thoanuom PHCU",
      "Thonyor PHCC",
      "Tiap PHCU",
      "TIEM PHCU",
      "Touchluak PHCU",
      "Tuet PHCU",
      "Tuoach Luak PHCU",
      "Turkey PHCU",
      "Tutnyang PHCU",
      "Waak PHCC",
      "Wanam PHCU",
      "Wangkei PHCC",
      "Wathnyotni PHCU",
      "Yoanyang PHCU",
      "Yub PHCU",
    ],
    "Pibor Administrative Area": [
      "Ajwara PHCU",
      "Boma PHCC",
      "Churri PHCC",
      "Daktek PHCU",
      "Gumuruk PHCU",
      "Hai Matar PHCU",
      "Kasingor PHCU",
      "Khoradep PHCU",
      "Labarab PHCU",
      "Lekuangole PHCU",
      "Matar HOSPITAL",
      "Meiwun PHCU",
      "Nyalangoro PHCU",
      "Nyat PHCU",
      "Nyium PHCU",
      "Oagn PHCC",
      "Obuodi PHCU",
      "Ojangbai PHCU",
      "Okadi PHCU",
      "Okadi PHCU",
      "Origena PHCU",
      "Otallo PHCU",
      "Pibor PHCC",
      "Pochalla PHCC",
      "Raad PHCU",
      "Thambeth PHCU",
      "Vertheth PHCU",
    ],
    "Jonglei State": [
      "Akeer (Ascom) PHCU",
      "Akobo HOSPITAL",
      "Akuai Deng PHCU",
      "Alela PHCU",
      "Amiel PHCU",
      "Anyak PHCU",
      "Anyidi PHCC",
      "Arek PHCU",
      "Ascom Ayod PHCC",
      "Atar PHCU",
      "Ayod PHCC",
      "Ayueldit PHCU",
      "Baidit PHCC",
      "Baping PHCU",
      "Bariak PHCU",
      "Bei PHCU",
      "Bor Prison PHCC",
      "Bor State Hospital",
      "Buom/Kolapach PHCU",
      "Buong PHCC",
      "Burmath PHCU",
      "Canal PHCC",
      "Chiban PHCU",
      "Chotbora PHCU",
      "Chuai PHCU",
      "Chuil PHCC",
      "Cuei Keer PHCU",
      "Cuei-Magon PHCU",
      "Dhorek PHCU",
      "Diel PHCU",
      "Dilule PHCU",
      "Diror PHCU",
      "Dong PHCU",
      "Dongchak PHCU",
      "Dorok PHCU",
      "Duk Lost Boy Hospital",
      "Fangak HOSPITAL",
      "Gakyuom PHCU",
      "Gorwai PHCC",
      "Gorwai PHCU",
      "Haat PHCU",
      "Haat PHCU",
      "Jalle PHCC",
      "Jarweng PHCU",
      "Jiech / Wau PHCC",
      "Juaibor PHCC",
      "Kaikuiny PHCC",
      "Kaikuiny PHCC",
      "Kalel PHCU",
      "Kandak PHCU",
      "Kapat PHCU",
      "Karam PHCC",
      "Keew PHCC",
      "Kharmun PHCU",
      "Khiir PHCU",
      "Khor Ardep PHCU",
      "Khorfulus PHCC",
      "Khorwac PHCC",
      "Khorwac PHCU",
      "Koat Nyakong PHCU",
      "kodalok PHCU",
      "Kolanyang PHCU",
      "Kolmerak PHCU",
      "Kolnyang PHCC",
      "Konbeek PHCU",
      "Kongor PHCC",
      "Kony PHCU",
      "Koyom Island PHCU",
      "Koyoom PHCU",
      "Kuachdeng PHCU",
      "Kuemduok PHCU",
      "Kuerdeng PHCU",
      "Kuernyang PHCC",
      "Kuerphon PHCU",
      "Langbar PHCU",
      "Lange PHCU",
      "Lankien PHCC",
      "Limkuon PHCU",
      "Lualdit PHCU",
      "Maar PHCC",
      "Maar PHCU",
      "Mabior PHCU",
      "Mabior PHCU",
      "Mabior PHCU",
      "Makol-Cuei PHCU",
      "Makuach PHCC",
      "Malek PHCU",
      "Malek PHCU",
      "Malek PHCU",
      "Malek PHCU",
      "Malek PHCU",
      "Malek PHCU",
      "Malek PHCU",
      "Malou PHCU",
      "Malou PHCU",
      "Malual Chaat PHCU",
      "Mandeng PHCU",
      "Mandeng PHCU",
      "Mandeng PHCU",
      "Manime PHCC",
      "Manyiel PHCU",
      "Manyiel PHCU",
      "Mareng PHCU",
      "Mareng PHCU",
      "Mathiang PHCU",
      "Mathiang PHCU",
      "Meer PHCU",
      "Meer PHCU",
      "Menime PHCU",
      "Modit PHCU",
      "Mogok PHCC",
      "Motot PHCC",
      "MSF-H PHCU",
      "New Fangak Lele PHCC",
      "Nomanyang PHCU",
      "Nukta Thoklial PHCC",
      "Nyadin PHCC",
      "Nyadiu PHCC",
      "Nyawit PHCU",
      "Old Akobo PHCU",
      "Old Fangak HOSPITAL",
      "Padek PHCC",
      "Padiet PHCC",
      "Pading PHCU",
      "Pagaak PHCC",
      "Pagil PHCC",
      "Pagok PHCU",
      "Paguir PHCU",
      "Pajiek PHCU",
      "Pajut Kurgai PHCC",
      "Pakaan PHCC",
      "Pakam PHCU",
      "Pakam PHCU",
      "Palabach PHCU",
      "Palieu PHCC",
      "Pamai PHCU",
      "Pangborong PHCU",
      "Panpadiar PHCU",
      "Panwel PHCU",
      "Panyagor County Hospital",
      "Panyang PHCU",
      "Panyang PHCU",
      "Pariak PHCC",
      "Patai PHCU",
      "Pathai PHCU",
      "Patiou PHCC",
      "Patuenoi PHCU",
      "Patuet PHCC",
      "Patuet PHCU",
      "Payai PHCU",
      "Pieri PHCC",
      "Pokbor PHCU",
      "Poktap PHCC",
      "Pulchol PHCC",
      "Pulita PHCU",
      "Pultruk PHCC",
      "Riang PHCU",
      "Riang PHCU",
      "Riang PHCU",
      "Riang PHCU",
      "Tangnyang PHCU",
      "Thokchak PHCU",
      "Thokliel PHCU",
      "Thotchok PHCU",
      "Thotwat PHCU",
      "Tiam PHCU",
      "Toch PHCU",
      "Tong PHCU",
      "Tut Majok PHCU",
      "Uror PHCU",
      "Waat PHCC",
      "Walgak PHCC",
      "Wan Machar PHCU",
      "Wangchoat PHCU",
      "Wanglel PHCU",
      "Wangulei PHCU",
      "Wau PHCU",
      "Wechding PHCU",
      "Wenyal PHCU",
      "Werkok PHCC",
      "Wunakot PHCU",
      "Wunbin PHCU",
      "Wunkiir PHCU",
      "Wunlem PHCU",
      "Yian PHCU",
      "Yidit PHCU",
      "Yuai PHCC",
      "Yuai PHCU",
    ],
    "Abyei Administrative Area": [
      "Abyei PHCC",
      "Agany Tok PHCU",
      "Agok MSF Hospital",
      "Agok PHCC",
      "Agok PHCC",
      "Amenth bek HOSPITAL",
      "Amiet PHCU",
      "Athony PHCU",
      "Athony PHCU",
      "Awal PHCU",
      "Awalnhom PHCU",
      "dokra PHCU",
      "Dongop PHCU",
      "Ganga PHCU",
      "Juljok PHCC",
      "Kolom PHCU",
      "Mabok PHCU",
      "Mading Achueng PHCU",
      "Mading Jok Thiang PHCU",
      "Maker PHCC",
      "Malual Aleiu PHCU",
      "Marial Achak PHCC",
      "Mijak PHCU",
      "Miodol PHCC",
      "Miyom Ngok PHCU",
      "Noong PHCU",
      "Rumamer PHCC",
      "Tagale PHCC",
      "Todaj PHCC",
      "Wunchuei PHCU",
      "Wunpeth PHCU",
      "Wunrok PHCU",
    ],
  },
];

// export const states = [
//   "Western Equatoria State",
//   "Lakes State",
//   "Eastern Equatoria State",
//   "Upper Nile State",
//   "Central Equatoria State",
//   "Warrap State",
//   "Ruweng Administrative Area",
//   "Northern Bahr El Ghazal State",
//   "Western Bahr El Ghazal State",
//   "Unity State",
//   "Unity State",
//   "Pibor Administrative Area",
//   "Jonglei State",
//   "Abyei Administrative Area",
// ];
